### ISSUE TITLE
Distributing CONTRIBUTING.pod

### ISSUE THREAD

**Issue by Grinnz** [wrog/ipromise#1]
All .pod files in the root directory of a distribution end up getting installed and similarly indexed on metacpan as documentation; this isn't appropriate for a CONTRIBUTING.pod any more than a README.pod. This is an unfortunate effect of backcompat code in ExtUtils::MakeMaker. Possible solutions are excluding the file from GatherDir, pruning it with PruneFiles, or changing it to a CONTRIBUTING.md (my preferred solution so that it ends up in the CPAN dist).

**Comment by wrog** [comment]
Ok, thanks.  fixed for next version, whenever that'll be (I assume I lose points if I do 2 in one day).

I'm still a bit confused because wouldn't a CONTRIBUTING.md **also** have to be indexed somewhere (since metacpan has to look up what to put in the "How to Contribute" link)? 

What's the extra work created by having it be a .pod?

**Comment by Grinnz** [comment]
This installation and indexing of files in the root is specially for .pod and .pm files, because that's how CPAN distributions were originally organized. Any other file extension doesn't get interpreted this way. Other indexing metacpan does on the file wouldn't consider it as documentation and would be appropriate to its purpose.
